---
# This is httpd installation as required

- name: install httpd as required
  become: yes
  hosts: all
  
  tasks:
    - name: install web service 
      yum:
         name: httpd
         state: present

    - name: start web server 
      service:
         name: httpd
         state: stated  
     

  