---
# This is user installation as required

- name: configured users as required 
  hosts: all
  vars:
  usersnames:
          - devs
          - security
          - admins
  become: yes

  tasks:       
          - group:
              name: web
              state: present

          - user:
              name: "{{item}}"
              state: present
              group: web
              append: yes
          - Withitems: "((user_names))"
          